# .github/workflows/build.yml

name: Build, Export and Publish Next.js App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      
      - name: Go to directory
        run: cd ./spin-blog/

      - name: Run trunk
        run: trunk build --release
      
      - name: Go back to root
        run: cd ..

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env: 
          REPO: self
          BRANCH: gh-pages
          FOLDER: spin-blog/dist
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
